### ISSUE TITLE
Missing support UTC timezone

### ISSUE THREAD

**Issue by alexmurray** [md-arif-shaikh/tzc#1]
Can you please add the UTC timezone? https://en.wikipedia.org/wiki/Coordinated_Universal_Time

**Comment by md-arif-shaikh** [comment]
Hi @alexmurray, thanks for this. Just to understand it more clearly, do you want to use offsets in the form of `UTC+-HH:MM`? Currently, it will work if you give `UTC+-HHMM` or in fact just `HHMM` as your zone input. Let me know if you still think I should include `UTC+-HH:MM` format. To be honest it would be trivial to support this but just wanted to check what you mean before I do so.

Also, would you prefer an option to choose which format to use?

**Comment by alexmurray** [comment]
I meant actually just having UTC in the list of supported / known timezones - so that say you could convert to/from a particular timezone to/from UTC.

**Comment by md-arif-shaikh** [comment]
Ah, I see. I can definitely do that. FYI, you can also do this by setting the `tzc-favourite-time-zones` variable. Like
```emacs-lisp
(setq tzc-favourite-time-zones '("UTC+0000" "Asia/Kolkata" "America/New_York"))
```

**Comment by md-arif-shaikh** [comment]
Hi @alexmurray, could you let me if the last commit fixed the issue for you?

**Comment by md-arif-shaikh** [comment]
I am closing this assuming it is no longer an issue. Feel free to reopen if it does not work for you.

**Comment by alexmurray** [comment]
Apologies I haven't had a chance to check on this, will let you know. Thanks again for the quick response.

**Comment by md-arif-shaikh** [comment]
Hi @alexmurray, I forgot to mention that there has been a change in the way you can set your preferred zones, it is now an `alist` where each element is of the form `('zone-info' 'label')`. For example, you can add `UTC` by setting
```emacs-lisp
(setq tzc-favourite-time-zones-alist '(("UTC+0000" "UTC") ("Asia/Kolkata" "Kolkata"))
```
or simply
```emacs-lisp
(setq tzc-favourite-time-zones-alist '(("+0000" "UTC") ("Asia/Kolkata" "Kolkata"))
```

**Comment by alexmurray** [comment]
Thanks - yep this works great.
